name: Keep Hugging Face Space Alive

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          curl --fail -s "https://abhshkgtm19:$HF_TOKEN@huggingface.co/spaces/abhshkgtm19/BTE-Predictor-App" || echo "Ping executed."
